name: Kitikiplot CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          sudo apt update
          source venv/bin/activate
          sudo apt install -y python3 python3-pip 
          pip install pytest


      - name: Install Required Python Packages
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          source venv/bin/activate
          cd  tests/unit_test
          pytest unit_test.py
